/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IWords } from "../IWords";

export class IWords__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): IWords {
    return new Contract(address, _abi, signerOrProvider) as IWords;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenIdToInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "starIcon",
        type: "string",
      },
      {
        internalType: "string",
        name: "background",
        type: "string",
      },
      {
        internalType: "string",
        name: "icon",
        type: "string",
      },
      {
        internalType: "string",
        name: "words",
        type: "string",
      },
      {
        internalType: "string",
        name: "author",
        type: "string",
      },
      {
        internalType: "string",
        name: "desc",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
